# Generated by Django 3.2.4 on 2021-07-12 09:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210711_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 12, 9, 17, 27, 475728, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 12, 9, 17, 27, 475728, tzinfo=utc)),
        ),
    ]
